spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mon_pfe?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# Configuration JWT
jwt:
  secret: aLonSecReTkEytHatIsHardToGuEssAndHasMiNimuMSiZe256BiTs
  expiration: 86400000     # 24 heures en millisecondes
  refresh-expiration: 604800000  # 7 jours en millisecondes

# Configuration serveur
server:
  port: 8080
  error:
    include-message: always 